(function($){function getSettingsObjFromTable(dt){var oDTSettings;if($.fn.dataTable.Api){oDTSettings=new $.fn.dataTable.Api(dt).settings()[0]}else if(dt.fnSettings){oDTSettings=dt.fnSettings()}else if(typeof dt==='string'){if($.fn.dataTable.fnIsDataTable($(dt)[0])){oDTSettings=$(dt).eq(0).dataTable().fnSettings()}}else if(dt.nodeName&&dt.nodeName.toLowerCase()==='table'){if($.fn.dataTable.fnIsDataTable(dt.nodeName)){oDTSettings=$(dt.nodeName).dataTable().fnSettings()}}else if(dt instanceof jQuery){if($.fn.dataTable.fnIsDataTable(dt[0])){oDTSettings=dt.eq(0).dataTable().fnSettings()}}else{oDTSettings=dt}
return oDTSettings}
if($.fn.dataTable){$.fn.dataTable.ext.search.push(function(settings,data,dataIndex){var $table=$(settings.nTable);var dTable=$table.DataTable();var sSettings=$table.data('dateRangeSearch');if(sSettings&&sSettings.hasOwnProperty('start')){var colDate=moment(data[sSettings.column-1],sSettings.format);var inRange=((colDate.isSame(sSettings.start)||colDate.isAfter(sSettings.start))&&(colDate.isSame(sSettings.end)||colDate.isBefore(sSettings.end)));return inRange}
return !0});$.fn.dataTableExt.oPagination.custom_box={"fnInit":function(oSettings,nPaging,fnCallbackDraw){var $gotoEl=$('<span class="paging-goto">Go to:</span>');var $pagingStatEl=$('<span class="paging-stat" />');var $inputEl=$('<input class="form-control paging-input" value="1" />');var $leftNavEl=$('<button class="btn btn-default paging-nav nav-left">&laquo;</button>');var $rightNavEl=$('<button class="btn btn-default paging-nav nav-right">&raquo;</button>');var $buttonGroup=$('<div class="btn-group paging-nav-group"></div>');var $showRowsEl=$('<span class="paging-rows">Show rows:</span>');var $selectEl=$('<select class="paging-rows-count form-control" data-selectbox="true"></select>');$selectEl.append('<option value="10">10</option>');$selectEl.append('<option value="25">25</option>');$selectEl.append('<option value="50">50</option>');$selectEl.append('<option value="100">100</option>');$selectEl.find('option').filter(function(){return($(this).val()==oSettings._iDisplayLength)}).prop('selected',!0);$buttonGroup.append($leftNavEl);$buttonGroup.append($rightNavEl);$(nPaging).append($showRowsEl);$(nPaging).append($selectEl);$(nPaging).append($gotoEl);$(nPaging).append($inputEl);$(nPaging).append($pagingStatEl);$(nPaging).append($buttonGroup);$selectEl.change(function(){oSettings._iDisplayLength=$selectEl.val();fnCallbackDraw(oSettings)});$leftNavEl.click(function(e){var iCurrentPage=Math.ceil(oSettings._iDisplayStart/oSettings._iDisplayLength)+1;if(iCurrentPage>1){oSettings._iDisplayStart=oSettings._iDisplayLength*(iCurrentPage-2);fnCallbackDraw(oSettings)}
e.preventDefault();return !1});$rightNavEl.click(function(e){var iCurrentPage=Math.ceil(oSettings._iDisplayStart/oSettings._iDisplayLength)+1;var iPages=Math.ceil((oSettings.fnRecordsDisplay())/oSettings._iDisplayLength);if(iCurrentPage<iPages){oSettings._iDisplayStart=oSettings._iDisplayLength*iCurrentPage;fnCallbackDraw(oSettings)}
e.preventDefault();return !1});$inputEl.on('keyup change',function(e){var passes=(e.type=='change'||(e.type=='keyup'&&e.which==13));if(passes){var thePage=parseInt($inputEl.val());if(isNaN(thePage))thePage=1;var iPages=Math.ceil((oSettings.fnRecordsDisplay())/oSettings._iDisplayLength);if(thePage>iPages)thePage=iPages;oSettings._iDisplayStart=oSettings._iDisplayLength*(thePage-1);fnCallbackDraw(oSettings)}});setTimeout(function(){var $table=$(oSettings.nTable)
var $tableWrapper=$(oSettings.nTableWrapper);if($table.data('ignorePaging')){$tableWrapper.find('.dataTables_paginate').hide(0)}
else{init_selectbox($tableWrapper)}},1)},"fnUpdate":function(oSettings,fnCallbackDraw){var $table=$(oSettings.nTable)
var $tableWrapper=$(oSettings.nTableWrapper);if(!$table.data('ignorePaging')){if(!oSettings.aanFeatures.p)return;var $inputEl=$(oSettings.aanFeatures.p).find('.paging-input');var $pagingStatEl=$(oSettings.aanFeatures.p).find('.paging-stat');var iCurrentPage=Math.ceil(oSettings._iDisplayStart/oSettings._iDisplayLength)+1;var iCurrentTarget=(iCurrentPage*oSettings._iDisplayLength);if(iCurrentTarget>oSettings.fnRecordsTotal())iCurrentTarget=oSettings.fnRecordsTotal();$pagingStatEl.text((oSettings._iDisplayStart+1)+' - '+iCurrentTarget+' of '+oSettings.fnRecordsTotal());$inputEl.val(iCurrentPage)}
var $info=$tableWrapper.find('.dataTables_info');setTimeout(function(){$info.html('');if($table.data('infoType')){var $compiled=$info.data('compiledInfo');if(!$compiled){if($table.data('infoType')=='button'){$compiled=$('<a class="nice-link"></a>');$compiled.attr('href',($table.data('infoLink')?$table.data('infoLink'):'javascript:void(0)'));$compiled.html($table.data('infoText'));if($table.data('infoClass'))$compiled.addClass($table.data('infoClass'));if($table.data('buttonTarget'))$compiled.data('target',$table.data('buttonTarget'));if($table.data('infoId'))$compiled.attr('id',$table.data('infoId'));if($table.data('infoCallback'))window[$table.data('infoCallback')]($compiled,oSettings,$table)}
else if($table.data('infoType')=='clone'){$compiled=$($table.data('infoClone')).clone()}
else if($table.data('infoType')=='callback'){$compiled=window[$table.data('infoCallback')](oSettings,$table)}
$info.data('compiled',$compiled)}
$info.append($compiled)}},1)}}}})(window.jQuery)